ci: Use custom runner for `bench.yml`
argumentcomputer/zk-light-clients pull request #187
Opened 2024-08-23 18:06 UTC by samuelburnham

- Switches from a self-hosted benchmark runner to a [Warpbuild custom runner](https://www.warpbuild.com/blog/launch-byoc), which handles spinning up and down the AWS instance, containerizing, and autoscaling the self-hosted runners.
- Adds default env vars for benchmarking and user input to customize

Successful run: https://github.com/argumentcomputer/ci-lab/actions/runs/10528494329

Requires further testing after merge

2024-08-24 10:52 UTC, tchataigner requested changes
Thanks this looks great, a few changes to make on the env variable if we want the flow to work I think.

2024-08-24 10:52 UTC, tchataigner commented on .github/workflows/bench.yml
> +          echo "RUST_LOG=debug" | tee -a $GITHUB_ENV
I think that if we want to run benchmarks we should remove this, as it costs us some efficiency at proving time.

2024-08-24 10:52 UTC, tchataigner commented on .github/workflows/bench.yml
> +          echo "SHARD_BATCH_SIZE=0" | tee -a $GITHUB_ENV
This is not possible with the current head of the `dev` branch of Sphinx. As @storojs72 's  work pointed out that we should set it to `16` and that's the default value, we should remove it.

2024-08-24 10:52 UTC, tchataigner commented on ethereum/light-client/Makefile
> +	cargo bench --features ethereum --bench $$bench
We could adapt this to:
```
RUSTFLAGS="-C target-cpu=native -C opt-level=3" \
SHARD_SIZE=4194304 \
SHARD_CHUNKING_MULTIPLIER=256 \
cargo bench --features ethereum --bench $$bench
```

2024-08-24 10:52 UTC, tchataigner commented on ethereum/light-client/Makefile
>  BENCH ?= e2e
```suggestion
BENCH ?= committee_change
```

2024-08-24 10:52 UTC, tchataigner commented on .github/workflows/bench.yml
> +          # Default benchmark settings optimized for Aptos, can be overwritten with `env` input
```suggestion
          # Default benchmark settings optimized for our Light Clients, can be overwritten with `env` input
```

2024-08-26 19:52 UTC, wwared commented on .github/workflows/bench.yml
> -          echo "SHARD_BATCH_SIZE=0" | tee -a $GITHUB_ENV
After https://github.com/argumentcomputer/sphinx/pull/163 we should be able to re-add `SHARD_BATCH_SIZE=0` everywhere, so we shouldn't need to remove those

We should also be able to add `RECONSTRUCT_COMMITMENTS=false` to the vars list, per discussion on zulip

cc @storojs72 that has been looking into these variables

2024-08-26 21:01 UTC, wwared approved these changes

2024-08-26 21:32 UTC, tchataigner approved these changes

2024-08-26 21:32 UTC, merged