feat: Update E2E Aptos bench
argumentcomputer/zk-light-clients pull request #196
Opened 2024-08-28 14:41 UTC by storojs72

This PR is a result of the work in context of LC cost incentives.

Using the fact that some particular benchmarking instance has own specific hardware characteristics (memory, number of CPU cores) and also using very specific programs (Aptos LC), one can iterate over values of the Sphinx environment variables ([d392acca](https://github.com/argumentcomputer/sphinx/commit/d392acca56fbaa0e4dd0b73cfab0414b4e321348) was used, which is current `dev`) and compare results, looking for more optimal configuration rather than recommended by SP1, which are still more generic as they naturally "recommend" configuration, appropriate for different use cases.

So, using `RECONSTRUCT_COMMITMENT="false"` and `SHARD_CHUNKING_MULTIPLIER=32` (additionally to already known `SHARD_BATCH_SIZE=0`), gives some boost in SNARK proving on `r7iz.metal-16xl`, giving ~593s, which is less than 10 minutes. 

For curious reviewers, this is the set of benches I executed on `r7iz.metal-16xl`:

```
{"e2e_proving_time":784640,"inclusion_proof":{"proving_time":747747,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":784640,"request_response_proof_size":28710},"reconstruct_commitments":"true","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"2","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":780460,"inclusion_proof":{"proving_time":745199,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":780460,"request_response_proof_size":28710},"reconstruct_commitments":"true","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"4","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":775601,"inclusion_proof":{"proving_time":746641,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":775601,"request_response_proof_size":28710},"reconstruct_commitments":"true","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"8","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":779283,"inclusion_proof":{"proving_time":746216,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":779283,"request_response_proof_size":28710},"reconstruct_commitments":"true","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"16","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":779577,"inclusion_proof":{"proving_time":765137,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":779577,"request_response_proof_size":28710},"reconstruct_commitments":"true","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"32","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":786710,"inclusion_proof":{"proving_time":744246,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":786710,"request_response_proof_size":28710},"reconstruct_commitments":"true","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"64","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":771666,"inclusion_proof":{"proving_time":744730,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":771666,"request_response_proof_size":28710},"reconstruct_commitments":"true","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"128","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":780117,"inclusion_proof":{"proving_time":745961,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":780117,"request_response_proof_size":28710},"reconstruct_commitments":"true","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"256","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":696794,"inclusion_proof":{"proving_time":658020,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":696794,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"32","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":685708,"inclusion_proof":{"proving_time":661794,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":685708,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"64","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":684964,"inclusion_proof":{"proving_time":654771,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":684964,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"128","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":685451,"inclusion_proof":{"proving_time":663992,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":685451,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"256","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":751135,"inclusion_proof":{"proving_time":689445,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":751135,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"2097152","shard_batch_size":"8","shard_chunking_multiplier":"32","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":686436,"inclusion_proof":{"proving_time":657872,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":686436,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"4194304","shard_batch_size":"8","shard_chunking_multiplier":"32","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":773814,"inclusion_proof":{"proving_time":745059,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":773814,"request_response_proof_size":28710},"reconstruct_commitments":"true","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"256","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":619908,"inclusion_proof":{"proving_time":619908,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":592407,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"4194304","shard_batch_size":"0","shard_chunking_multiplier":"8","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":685638,"inclusion_proof":{"proving_time":660375,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":685638,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"4194304","shard_batch_size":"8","shard_chunking_multiplier":"8","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":687725,"inclusion_proof":{"proving_time":657319,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":687725,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"4194304","shard_batch_size":"16","shard_chunking_multiplier":"8","rustflags":"-C target-cpu=native --cfg tokio_unstable -C opt-level=3"}
{"e2e_proving_time":619908,"inclusion_proof":{"proving_time":619908,"request_response_proof_size":18600},"epoch_change_proof":{"proving_time":592407,"request_response_proof_size":28710},"reconstruct_commitments":"false","shard_size":"4194304","shard_batch_size":"0","shard_chunking_multiplier":"8","rustflags":"-C target-cpu=native --cfg toki [...]

2024-08-28 15:19 UTC, wwared submitted a review, later dismissed
This looks fine to me, thanks for looking into this :pray:

2024-08-28 16:08 UTC, tchataigner requested changes
Could you change the documentation of the Light Clients to advise running on a 16xl machine with the environment variables that need to be set?

2024-08-29 15:00 UTC, wwared approved these changes

2024-08-29 15:02 UTC, tchataigner approved these changes

2024-08-29 15:03 UTC, merged